services:
  - type: web
    name: horaire-site
    env: python
    plan: free
    buildCommand: ""
    startCommand: ""
    staticPublishPath: database

  - type: cron
    name: horaire-cron
    env: python
    schedule: "30 0,8,12 * * *"
    buildCommand: ""
    startCommand: python3 horaire/main.py
